export const MODELS = [
  {
    key: "grab",
    name: "Grab & Go",
    franchiseFee: "₹2.99 Lakhs + GST",
    area: "50 - 100 sq.ft",
    setupType: "Kiosk Setup",
    idealFor: "Food Courts, IT Parks, Cinemas, Airports, Colleges",
    menu: "Ice creams, Sundaes, Shakes & more",
    team: "1 Staff + 1 Manager",
    setupCost: "Up to ₹24.00 Lakhs",
    totalInvestment: "Up to ₹7.00 Lakhs",
    avgMonthlySales: 300000,
    expenses: 67500,
    netProfit: 67500,
    grossProfit: 135000,
  },
  {
    key: "urban",
    name: "Urban Junction",
    franchiseFee: "₹4.99 Lakhs + GST",
    area: "250 - 400 sq.ft",
    setupType: "Premium Ice Cream Café Outlet",
    idealFor: "High footfall urban areas",
    menu: "Sundaes, Falooda, Burgers & more",
    team: "4 Staff + 1 Manager",
    setupCost: "Up to ₹210.00 Lakhs",
    totalInvestment: "Up to ₹20.00 Lakhs",
    avgMonthlySales: 550000,
    expenses: 127500,
    netProfit: 120000,
    grossProfit: 247500,
  },
  {
    key: "metro",
    name: "Metro Junction",
    franchiseFee: "₹24.99 Lakhs",
    area: "500 - 800 sq.ft",
    setupType: "Full-Scale Premium Café Outlet",
    idealFor: "Flagship locations & premium high-traffic areas",
    menu: "Ice creams, Fried Chicken & more",
    team: "5 Staff + 1 Manager",
    setupCost: "Up to ₹212.50 Lakhs",
    totalInvestment: "Up to ₹25.00 Lakhs",
    avgMonthlySales: 750000,
    expenses: 162500,
    netProfit: 175000,
    grossProfit: 337500,
  },
];